path:  D:/2.file/Code/Code_files/2025.2.4_YOLOv11-seg/data/train_data/Cells_3channel/yolo

train:  D:/2.file/Code/Code_files/2025.2.4_YOLOv11-seg/data/train_data/Cells_3channel/yolo/images/train
val:  D:/2.file/Code/Code_files/2025.2.4_YOLOv11-seg/data/train_data/Cells_3channel/yolo/images/test
test:  D:/2.file/Code/Code_files/2025.2.4_YOLOv11-seg/data/train_data/Cells_3channel/yolo/images/test

nc: 1

names:
  0: centrosome
